M48
; DRILL file {KiCad 8.0.3} date 2024-08-19T01:24:24-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-19T01:24:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.785
%
G90
G05
T1
X103.505Y-59.055
X147.955Y-59.055
T2
X138.43Y-148.768
M30
